### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yixiaojiu** [yixiaojiu/kimika#3]
- [x] Remote server select
- [x] Redraw the diagram using https://excalidraw.com/
- [ ] optimize kimika/src/utils/select.rs
- [ ] make server configurable
- [ ] optimize transfer speed
